version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    build: .
    command: yarn prod
    depends_on:
      - redis
    env_file: ./.env
    ports:
      - ${PORT}:${PORT}
    restart: "always"
