version: '3'

services:
  redis:
    image: redis:alpine
    ports: 
      - "6379:6379"

  app:
    build: .
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production
    restart: always
    ports: 
      - "3030:3030"
    depends_on:
      - redis