version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    image: node:alpine
    command: yarn dev
    depends_on:
      - redis
    env_file: ./.env.dev
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app
    working_dir: /app
