version: "3"

services:
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"
    expose:
      - '6379'
    networks:
      - webnet

  app:
    build: .
    command: yarn prod
    depends_on:
      - redis
    env_file: ./.env
    ports:
      - ${PORT}:${PORT}
    restart: "always"
    networks:
      - webnet

networks:
  webnet:
